version: '3'
services:
  rtsp-simple-server:
    container_name: rtsp-simple-server
    image: aler9/rtsp-simple-server
    environment:
      - RTSP_PROTOCOLS=tcp
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
    # restart: always
